### ISSUE TITLE
Get rid of `xargs`

### ISSUE THREAD

**Issue by vktec** [torbaytechjam/packageinstaller#1]
`xargs` should not be used without `-0` and is very rarely needed, as there are safer and often easier ways to do what `xargs` does.

As an example, this line in `install.sh`:

``` bash
xargs -a $(awk '/^\s*[^#]/' "$packagelist") -r -- sudo apt-get -y install
```

Should look more like:

``` bash
sudo apt-get -y install $(cat $packagelist)
```

This is for a number of reasons:
1. `xargs` is not needed, and this can be achieved more elegantly using `cat`
2. The way `awk` is used here causes it to read from a file, which is unneeded, as you're using `xargs -a` anyway (which can, of course, be achieved more easily using `$()` and `cat`

I'm happy to submit a pull request if necessary, but I wanted to explain _why_ these changes are necessary, as hopefully @zleap can learn from this :)

**Comment by vktec** [comment]
@zleap this could be useful: http://mywiki.wooledge.org/BashGuide
Also, consider joining #bash on freenode

**Comment by zleap** [comment]
Ok fixed, thanks, I have just commented out the old line,  so we can perhaps use that as a teaching point later.

**Comment by vktec** [comment]
Hmm... I would just remove it, but it's your call

**Comment by vktec** [comment]
Also, the new version is under the `#wget s4a` comment.
